spring:
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    ignore-migration-patterns: "*:Missing"

logging:
  level:
    com.crichere: DEBUG
    org.springframework.security: DEBUG

crichere:
  cors:
    allowed-origins: "*"
