ALTER TABLE users ADD COLUMN IF NOT EXISTS suspended BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS suspension_reason TEXT;

ALTER TABLE leagues ADD COLUMN IF NOT EXISTS suspended BOOLEAN DEFAULT FALSE;
ALTER TABLE leagues ADD COLUMN IF NOT EXISTS suspension_reason TEXT;
ALTER TABLE leagues ADD COLUMN IF NOT EXISTS waiting_list_mode VARCHAR(50) DEFAULT 'ADMIN_PICKS';
ALTER TABLE leagues ADD COLUMN IF NOT EXISTS plan_type VARCHAR(50);
ALTER TABLE leagues ADD COLUMN IF NOT EXISTS plan_expires_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE league_players ADD COLUMN IF NOT EXISTS auction_eligible BOOLEAN DEFAULT FALSE;
