ALTER TABLE leagues ADD COLUMN format VARCHAR(100);
ALTER TABLE leagues ADD COLUMN rules_url VARCHAR(500);
ALTER TABLE leagues ADD COLUMN must_sell_all BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE leagues ADD COLUMN player_order_mode VARCHAR(50) NOT NULL DEFAULT 'RANDOM';
