ALTER TABLE auctions ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE player_auction_states ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE franchise_purse_states ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
